[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --optimize-autoloader && npm ci && npm run build && php artisan storage:link && php artisan key:generate --force"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"
healthcheckPath = "/health"
healthcheckTimeout = 60

[deploy.vars]
APP_ENV = "production"
DB_CONNECTION = "sqlite"
DB_DATABASE = "/app/database/database.sqlite"
CACHE_DRIVER = "file"

[nixpacks]
php-version = "8.2"
node-version = "20"
