[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --optimize-autoloader && npm ci && npm run build:prod"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"
