[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && php artisan storage:link && php artisan config:cache"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"