[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && mkdir -p /app/storage && touch /app/storage/database.sqlite && chmod -R 777 /app/storage && php artisan config:cache"

[deploy]
startCommand = "php artisan serve --host 0.0.0.0 --port $PORT"
