[build]
builder = "nixpacks"
buildCommand = "rm -rf node_modules && npm install --force && npm run build && php artisan storage:link && php artisan config:clear && php artisan cache:clear && php artisan config:cache"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"