[build]
builder = "nixpacks"
buildCommand = """
    mkdir -p public/build && \
    chmod -R 775 public/build && \
    npm install && \
    npm run build && \
    ls -la public/build && \
    mkdir -p storage/framework/{sessions,views,cache} && \
    mkdir -p storage/app/public && \
    touch storage/database.sqlite && \
    chmod -R 775 storage bootstrap/cache && \
    php artisan storage:link && \
    php artisan migrate --force && \
    php artisan config:cache && \
    php artisan route:cache && \
    php artisan view:cache && \
    cat public/build/manifest.json || echo "Manifest not found!"
"""

[deploy]
startCommand = "php artisan serve --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"