[build]
builder = "nixpacks"
buildCommand = """
    npm install && npm run build && \
    mkdir -p storage/framework/{sessions,views,cache} && \
    mkdir -p storage/app/public && \
    touch storage/database.sqlite && \
    chmod -R 775 storage bootstrap/cache && \
    php artisan storage:link && \
    php artisan optimize:clear && \
    php artisan config:clear && \
    php artisan cache:clear && \
    php artisan route:clear && \
    php artisan view:clear && \
    php artisan migrate --force
"""

[deploy]
startCommand = "php-fpm -D && nginx -g 'daemon off;'"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
