[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build && php artisan config:cache && php artisan migrate --force"

[deploy]
startCommand = "php artisan serve --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
